# Configurable values.  Change these, `make clean` and `make` to run
# an analysis with these new values.

mutprobs := 0.02
nmutprobs := $(words $(mutprobs))

problems := $(wildcard ../../input/*.cnf)
nproblems := $(words $(problems))

nreps := 6

timeout := 600
