# Configurable values.  Change these, `make clean` and `make` to run
# an analysis with these new values.

radiuses := 3
nradiuses := $(words $(radiuses))

problems := $(wildcard ../../input/*.cnf)
nproblems := $(words $(problems))

nreps := 6

timeout := 600
prunefract := 0.99
